# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-python-template
author_email: Chad Malfait
author_name: John Doe
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: murphy

